import time
import asyncio
import os
import sys

# Force UTF-8 encoding for stdout/stderr to prevent ASCII encoding errors
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8', errors='ignore')
if sys.stderr.encoding != 'utf-8':
    sys.stderr.reconfigure(encoding='utf-8', errors='ignore')

# Filter GRPC/ABSL logs before imports
os.environ["GRPC_VERBOSITY"] = "ERROR"
os.environ["GLOG_minloglevel"] = "2"

import email
import warnings
import logging
import markdown

# Suppress warnings and library logs
warnings.filterwarnings("ignore")
logging.getLogger("google.genai").setLevel(logging.ERROR)
logging.getLogger("httpx").setLevel(logging.ERROR)
logging.getLogger("tornado.access").setLevel(logging.ERROR)

from dotenv import load_dotenv
from state import StateManager
from brain import AgentBrain
from tools import AgentTools
from email_ops import EmailClient
from dashboard import DashboardLogger

# Load env variables
load_dotenv()

DEV_EMAIL = "chinmaydhok2013@gmail.com"

import html
from datetime import datetime
import re

def sanitize_text(text):
    """Removes surrogate characters and ensures UTF-8 compatibility."""
    if not text:
        return ""
    try:
        # Encode to utf-8 forcing surrogates to be replaced/ignored, then decode back
        return text.encode('utf-8', 'ignore').decode('utf-8')
    except Exception:
        return "Content could not be decoded."

def get_display_id(subject, thread_id):
    """Extracts a clean Ticket ID from subject or shortens the Message-ID."""
    # Try to find Ticket#YYYYMMDD-NNNNNN or TICKET-YYYYMMDD-NNN
    match = re.search(r"((?:Ticket#|TICKET-)[0-9A-Za-z-]+)", subject, re.IGNORECASE)
    if match:
        return match.group(1).upper()
    
    # Fallback to shortening the Message-ID
    clean_id = thread_id.strip("<>")
    if "@" in clean_id:
        clean_id = clean_id.split("@")[0]
    
    # If it's very long, truncate
    if len(clean_id) > 20:
        return f"...{clean_id[-10:]}"
    return clean_id

def get_readable_state(state):
    """Maps internal state to user-friendly label."""
    mapping = {
        "NEW": "New Request",
        "WAITING_APPROVAL": "1/2 User Plan Review",
        "WAITING_DEV_APPROVAL": "Build in review with developer",
        "COMPLETED": "Completed",
        "BLOCKED": "Blocked"
    }
    return mapping.get(state, state)

def get_email_template(title, content, action_text=None, action_command=None, color="#4F46E5", display_id=None, state=None, pr_url=None):
    # Sanitize and Escape HTML
    title = html.escape(sanitize_text(title))
    
    ticket_display = html.escape(str(display_id)) if display_id else "N/A"
    
    # Get readable state
    readable_state = get_readable_state(state)
    state_display = html.escape(str(readable_state)) if state else "N/A"
    
    date_display = datetime.now().strftime("%Y-%m-%d %H:%M")

    meta_html = ""
    if display_id or state:
        pr_html = ""
        if pr_url:
            pr_html = f"""
            <div style="margin-top: 8px; padding-top: 8px; border-top: 1px dashed #d1d5db;">
                <b>PR Link:</b> <a href="{pr_url}" style="color: #059669; font-weight: bold;">{pr_url}</a>
            </div>
            """
            
        meta_html = f"""
        <div style="background-color: #f3f4f6; padding: 10px 24px; font-size: 0.85em; color: #6b7280; border-bottom: 1px solid #e5e7eb;">
            <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
                <span><b>ID:</b> {ticket_display}</span>
                <span><b>Time:</b> {date_display}</span>
            </div>
            <div>
                <span><b>Status:</b> <span style="background-color: #e5e7eb; padding: 2px 6px; border-radius: 4px; font-family: monospace; border: 1px solid #d1d5db; color: #374151;">{state_display}</span></span>
            </div>
            {pr_html}
        </div>
        """

    html_template = f"""
    <div style="font-family: 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="text-align: center; background-color: white; padding: 12px; border-bottom: 1px solid #e5e7eb;">
             <img src="https://instasize.com/api/image/4e76861d6fb4c8ccb704a87644c91657d025f13a4fe6e44778c89d991dcd45a8.jpeg" alt="Osmos AI" style="max-height: 32px;">
        </div>
        <div style="background-color: {color}; padding: 20px; text-align: center;">
            <h2 style="color: white; margin: 0;">{title}</h2>
        </div>
        {meta_html}
            {content}
            <div style="text-align: center; margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.8em;">
                Generated by CodeCrafter AI 🤖 this bot is from osmos <img src="https://instasize.com/api/image/4e76861d6fb4c8ccb704a87644c91657d025f13a4fe6e44778c89d991dcd45a8.jpeg" style="height: 12px; vertical-align: middle; margin-left: 4px;">
            </div>
        </div>
        """
    if action_text and action_command:
        html_template += f"""
        <div style="background-color: #f9fafb; padding: 16px; text-align: center; border-top: 1px solid #e5e7eb;">
            <p style="margin-bottom: 8px; font-weight: 500;">{action_text}</p>
            <div style="background-color: #e5e7eb; color: #1f2937; padding: 8px 16px; border-radius: 4px; display: inline-block; font-family: monospace; font-weight: bold;">
                Reply "{action_command}"
            </div>
        </div>
        """
    html_template += "</div>"
    return html_template

def main():
    print("Starting CodeCrafter Agent (Version 1)...")
    
    state_manager = StateManager()
    email_client = EmailClient()
    brain = AgentBrain()
    tools = AgentTools()
    dashboard = DashboardLogger()
    
    # Initial Repo Setup
    repo_url = os.getenv("REPO_URL")
    tools.clone_or_pull(repo_url)

    while True:
        try:
            print("Polling for emails...")
            mail = email_client.connect_imap()
            mail.select("inbox")
            
            # Search for creating new threads or replying
            status, messages = mail.search(None, 'UNSEEN')
            
            email_ids = messages[0].split()
            if email_ids:
                print(f"Queue Status: Found {len(email_ids)} new email(s). Processing batch...")

            for num in email_ids:
                try:
                    status, msg_data = mail.fetch(num, '(RFC822)')
                    raw_email = msg_data[0][1]
                    msg = email.message_from_bytes(raw_email)
                    
                    subject = msg["Subject"]
                    sender = email.utils.parseaddr(msg["From"])[1] # Extract email only
                    msg_id = msg["Message-ID"]
                    body = email_client.get_body(msg)

                    # Aggressive Sanitization at Ingres
                    subject = sanitize_text(subject)
                    sender = sanitize_text(sender)
                    body = sanitize_text(body)
                    
                    # Check State
                    refs = msg.get("References", "")
                    if refs:
                        thread_id = refs.split()[0].strip()
                    else:
                        thread_id = msg.get("In-Reply-To", msg_id) 
                    
                    current_state = state_manager.get_state(thread_id)
                    
                    # --- FALLBACK: If State is NEW, try matching by Subject ---
                    if current_state == "NEW":
                         existing_id = state_manager.find_thread_id_by_subject(subject)
                         if existing_id:
                             print(f"  [Info] Linked to existing thread by subject: {existing_id}")
                             thread_id = existing_id
                             current_state = state_manager.get_state(thread_id)
                    # ------------------------------------------------------------
                    
                    # --- TICKET ID GENERATION (Ingress) ---
                    thread_data = state_manager.get_thread_data(thread_id)
                    if "ticket_id" not in thread_data:
                        # New ticket or existing one without ID
                        if current_state == "NEW": # Only generate for genuinely new
                             new_ticket_id = state_manager.generate_ticket_id()
                             state_manager.update_state(thread_id, current_state, extra_data={"ticket_id": new_ticket_id})
                             thread_data["ticket_id"] = new_ticket_id
                             print(f"  [Accession] Generated Ticket ID: {new_ticket_id}")
                    
                    # Use stored ticket_id if available, else fallback
                    disp_id = thread_data.get("ticket_id")
                    if not disp_id:
                        disp_id = get_display_id(subject, thread_id)
                    # ---------------------------------------

                    # Log Initial State (NEW) if newly generated
                    if current_state == "NEW":
                        dashboard.log_ticket({
                            "ticket_id": disp_id,
                            "title": subject,
                            "requested_by": sender,
                            "created_at": datetime.now().isoformat(),
                            "status": "NEW"
                        })

                    try:
                        print(f"Processing ({sender}): {subject} | Ticket: {disp_id} | State: {current_state}")
                    except Exception:
                        print(f"Processing (Cleaned Log) | State: {current_state}")

                    # --- TERMINAL STATE CHECK ---
                    if current_state in ["COMPLETED", "BLOCKED"]:
                        print(f"  [Skipped] Ticket {disp_id} is in terminal state: {current_state}")
                        continue
                    # ----------------------------

                    # --- SENTINEL CHECK (New Threads Only) ---
                    if current_state == "NEW":
                        print(f"Ticket Analysed: {subject}")
                        print("Security Check: In Progress...")
                        try:
                            import json
                            sentinel_resp_str = asyncio.run(brain.sanitize_request(body))
                            sentinel_data = json.loads(sentinel_resp_str)
                            
                            if sentinel_data.get("status") == "BLOCKED":
                                reason = sentinel_data.get("reason", "Unknown security policy violation.")
                                print(f"Security Check: FAILED | Reason: {reason}")
                                
                                # 1. Notify User
                                email_client.send_reply(sender, subject, f"Security Alert: Your request was blocked.\nReason: {reason}", msg_id)
                                
                                # 2. Notify Developer
                                dev_alert_body = f"""
                                <p><b>Requestor:</b> {sender}</p>
                                <p><b>Blocked Reason:</b> <span style="color: #DC2626; font-weight: bold;">{reason}</span></p>
                                <hr>
                                <p><b>Original Request:</b></p>
                                <pre style="background: #f3f4f6; padding: 10px; white-space: pre-wrap;">{html.escape(body[:500])}</pre>
                                """
                                dev_msg = get_email_template(
                                    "COMBAT BLOCKED: Security Alert \U0001F6A8", 
                                    dev_alert_body,
                                    color="#DC2626", # Red
                                    display_id=disp_id,
                                    state="BLOCKED"
                                )
                                email_client.send_reply(DEV_EMAIL, subject, dev_msg, msg_id, is_html=True)

                                # 3. Update State
                                state_manager.update_state(thread_id, "BLOCKED", extra_data={"blocking_reason": reason})
                                continue
                            
                            body = sentinel_data.get("sanitized_input", body)
                            print(f"Security Check: PASS | Sanitization: YES")
                            
                        except Exception as e:
                            print(f"Security Check: ERROR ({e}). Defaulting to ALLOW.")
                    # ----------------------

                    # STATE MACHINE
                    
                    # 1. NEW or WAITING_APPROVAL (User Interaction)
                    # 1. NEW (Auto-Execution Phase)
                    # 1. NEW (Auto-Execution Phase)
                    if current_state == "NEW":
                        # --- PHASE 1: IMMEDIATE NOTIFICATION (User) ---
                        print("Notifying User (Immediate)...")
                        email_body = get_email_template(
                            f"Ticket In Progress: {disp_id}", 
                            f"""
                            <p>We have received your request and CodeCrafter is working on it.</p>
                            <p><b>Request:</b> {subject}</p>
                            <hr>
                            <p><b>Security Check:</b> <span style="color:#059669; font-weight:bold;">Passed \u2705</span></p>
                            <p><b>Status:</b> 🏗️ Build & Review in progress with Developer</p>
                            <p>You will be notified once the changes are live or if further input is needed.</p>
                            <div style="font-size: 0.9em; color: #6b7280; margin-top: 10px;">
                                *No action required from you at this stage.*
                            </div>
                            """, 
                            color="#3B82F6", # Blue
                            display_id=disp_id,
                            state="IN_PROGRESS"
                        )
                        email_client.send_reply(sender, f"In Progress: {subject}", email_body, msg_id, is_html=True)

                        # Log State (IN_PROGRESS)
                        dashboard.log_ticket({
                            "ticket_id": disp_id,
                            "title": subject,
                            "requested_by": sender,
                            "status": "IN_PROGRESS"
                        })

                        # --- PHASE 2: PLANNING ---
                        print("Drafting Plan...")
                        repo_tree = tools.list_dir()
                        
                        # Load Context
                        repo_context = ""
                        try:
                            if os.path.exists("repo_clone/llm.md"):
                                with open("repo_clone/llm.md", "r", encoding="utf-8") as f:
                                    repo_context += f"\n--- llm.md ---\n{f.read()}\n"
                            if os.path.exists("repo_clone/README.md"):
                                with open("repo_clone/README.md", "r", encoding="utf-8") as f:
                                    repo_context += f"\n--- README.md ---\n{f.read()}\n"
                        except Exception as e:
                            print(f"  [Warning] Context load failed: {e}")

                        plan = brain.analyze_request(body, repo_tree, context=repo_context)
                        
                        # --- PHASE 3: EXECUTION (Coding & QA) ---
                        print("Generating Code...")
                        code_response = brain.generate_code(plan)
                        
                        print("Running QA Check...")
                        diff = tools.get_current_diff()
                        qa_report = brain.review_code(diff, context=repo_context)
                        
                        # Prepare Reports for Developer
                        code_html = markdown.markdown(sanitize_text(code_response), extensions=['fenced_code', 'codehilite'])
                        qa_html = markdown.markdown(sanitize_text(qa_report), extensions=['fenced_code', 'codehilite'])
                        
                        # --- PHASE 4: NOTIFY DEVELOPER (Handover) ---
                        print("Requesting Developer Review...")
                        
                        dev_content = f"""
                        <p><b>Requestor:</b> {sender}</p>
                        <p><b>User Request:</b> {subject}</p>
                        <hr style="border:0; border-top:1px solid #eee;">
                        
                        <h4>\U0001F4DD Implementation Plan</h4>
                        <pre style="background:#f9fafb; padding:10px; max-height:200px; overflow:auto;">{html.escape(plan)}</pre>
                        
                        <h4>\U0001F4BB Changes Summary (Diff Match)</h4>
                        <div>{code_html}</div>
                        
                        <h4>\U0001F50D QA Report</h4>
                        <div style="background:#fefce8; padding:10px; border:1px solid #eab308; border-radius:4px;">
                            {qa_html}
                        </div>
                        """
                        dev_msg = get_email_template(
                            "Code Review Request",
                            dev_content,
                            "To proceed, reply with one of the following commands:",
                            "APPROVE / REJECT",
                            color="#6366F1", # Indigo
                            display_id=disp_id,
                            state="WAITING_DEV_APPROVAL"
                        )
                        
                        # Send to Dev (or Finder logic). Here we look for DEV_EMAIL or fallback to sender if testing.
                        recipient = DEV_EMAIL if DEV_EMAIL else sender
                        email_client.send_reply(recipient, f"Review REQ: {subject}", dev_msg, msg_id, is_html=True)
                        
                        # Update State
                        state_manager.update_state(thread_id, "WAITING_DEV_APPROVAL", plan, extra_data={
                            "ticket_id": disp_id,
                            "diff_summary": code_response,
                            "qa_report": qa_report,
                            "requested_by": sender,
                            "title": subject
                        })
                        print(f"  [State] Updated to WAITING_DEV_APPROVAL")
                        
                        # Log State (WAITING_DEV)
                        dashboard.log_ticket({
                            "ticket_id": disp_id,
                            "title": subject,
                            "requested_by": sender,
                            "status": "WAITING_DEV_APPROVAL"
                        })

                    # 2. WAITING_DEV_APPROVAL (Developer Interaction)
                    # 2. WAITING_DEV_APPROVAL (Developer Interaction)
                    elif current_state == "WAITING_DEV_APPROVAL":
                        # STRICT CHECK: Only Developer can approve
                        if sender == DEV_EMAIL:
                            upper_body = body.upper()
                            
                            # A. APPROVE
                            if "APPROVE" in upper_body or "MERGE" in upper_body: 
                                print("Developer Approval Received. Creating PR...")
                                
                                thread_data = state_manager.get_thread_data(thread_id)
                                qa_report = thread_data.get("qa_report", "")
                                diff_summary = thread_data.get("diff_summary", "")
                                original_requestor = thread_data.get("requested_by", "Unknown")

                                # Create PR
                                branch = f"fix/auto-{int(time.time())}"
                                pr_body = f"Implemented for {original_requestor}.\n**Approved By:** {sender}\n\n## \U0001F4DD Changes Summary\n{sanitize_text(diff_summary)}\n\n## \U0001F50D QA Report\n{sanitize_text(qa_report)}"
                                
                                pr_url = tools.create_pr(
                                    branch, 
                                    f"Auto-Fix: {subject}", 
                                    pr_body, 
                                    diff_summary
                                )
                                
                                # Log to Consolidated Dashboard (Lean)
                                dashboard.log_ticket({
                                    "ticket_id": disp_id,
                                    "title": subject,
                                    "requested_by": original_requestor,
                                    "status": "COMPLETED",
                                    "pr_url": pr_url
                                })
                                
                                # 1. Final Email to USER (Simple, Approved By Dev)
                                user_content = f"""
                                <p>The Pull Request has been generated.</p>
                                <p><b>Approved By:</b> {sender}</p>
                                <hr>
                                <p>Please contact the developer ({sender}) for more information or deployment.</p>
                                <p>This ticket is now <b>COMPLETED</b>.</p>
                                """
                                user_msg = get_email_template(
                                    "\U0001F512 Ticket Closed",
                                    user_content,
                                    color="#059669", # Dark Green
                                    display_id=disp_id,
                                    state="COMPLETED",
                                )
                                email_client.send_reply(original_requestor, subject, user_msg, msg_id, is_html=True)
                                
                                # 2. Final Email to DEVELOPER (With Link)
                                dev_content = f"""
                                <p>Pull Request Created Successfully.</p>
                                <div style="text-align: center; margin: 24px 0;">
                                    <a href="{pr_url}" style="background-color: #10B981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">View Pull Request</a>
                                </div>
                                <p>The user has been notified.</p>
                                """
                                dev_msg = get_email_template(
                                    "\U0001F680 PR Created",
                                    dev_content,
                                    color="#059669", # Dark Green
                                    display_id=disp_id,
                                    state="COMPLETED",
                                    pr_url=pr_url
                                )
                                email_client.send_reply(sender, subject, dev_msg, msg_id, is_html=True)
                                
                                print(f"SUCCESS: PR Created at {pr_url}")
                                state_manager.update_state(thread_id, "COMPLETED")
                                
                            # B. REJECT
                            elif "REJECT" in upper_body or "BLOCK" in upper_body:
                                print("Developer REJECTED the changes.")
                                
                                thread_data = state_manager.get_thread_data(thread_id)
                                original_requestor = thread_data.get("requested_by", "Unknown")
                                
                                # Notify User (Rejection)
                                reject_msg = get_email_template(
                                    "Request Rejected 🛑",
                                    f"""
                                    <p>The Developer has reviewed the changes and <b>REJECTED</b> this request.</p>
                                    <p><b>Reason/Comment:</b> (See developer reply below)</p>
                                    <hr>
                                    <p>This ticket is now <b>BLOCKED/CANCELLED</b>.</p>
                                    """,
                                    color="#EF4444", # Red
                                    display_id=disp_id,
                                    state="BLOCKED"
                                )
                                email_client.send_reply(original_requestor, subject, reject_msg, msg_id, is_html=True)
                                
                                # Notify Dev (Confirmation)
                                dev_confirm = get_email_template(
                                    "Ticket Cancelled",
                                    "<p>You have rejected this request. The user has been notified.</p>",
                                    color="#EF4444", # Red
                                    display_id=disp_id,
                                    state="BLOCKED"
                                )
                                email_client.send_reply(sender, subject, dev_confirm, msg_id, is_html=True)
                                
                                state_manager.update_state(thread_id, "BLOCKED", extra_data={"blocking_reason": "Developer Rejected"})
                                
                                # Log State (BLOCKED)
                                dashboard.log_ticket({
                                    "ticket_id": disp_id,
                                    "title": subject,
                                    "requested_by": original_requestor,
                                    "status": "BLOCKED"
                                })
                                
                            else:
                                print(f"  [Dev Pending] Message in thread, but no APPROVE/REJECT command.")
                        else:
                            print(f"  [Ignored] Non-Dev ({sender}) attempted to interact in DEV_APPROVAL state.")

                except Exception as e:
                    import traceback
                    traceback.print_exc()
                    print(f"Error processing email {num}: {e}")
                    continue

        except Exception as e:
            print(f"Critical error in poll loop: {e}")
        
        time.sleep(10)

if __name__ == "__main__":
    main()