import os

from github import Github
from git import Repo

class AgentTools:
    def __init__(self, repo_path="./repo_clone"):
        self.repo_path = os.path.abspath(repo_path)
        self.github_token = os.getenv("GITHUB_TOKEN")
        
    def clone_or_pull(self, repo_url):
        # Inject Token into URL for headless auth
        if self.github_token and repo_url.startswith("https://"):
            auth_url = repo_url.replace("https://", f"https://{self.github_token}@")
        else:
            auth_url = repo_url

        if os.path.exists(self.repo_path):
            try:
                repo = Repo(self.repo_path)
                # Update remote URL to ensure token is used/updated
                repo.remotes.origin.set_url(auth_url)
                print(f"  [Git] Pulling changes (Headless)...")
                repo.remotes.origin.pull()
            except Exception as e:
                # If pull fails, might be dirty tree. Stash or just log.
                print(f"  [Git] Pull failed: {e}")
        else:
            print(f"  [Git] Cloning repo (Headless)...")
            Repo.clone_from(auth_url, self.repo_path)
        return "Repository updated."

    def list_dir(self, rel_path="."):
        """Lists files in directory, ignoring git/node_modules."""
        target = os.path.join(self.repo_path, rel_path)
        items = []
        for root, dirs, files in os.walk(target):
            # Prune directories
            dirs[:] = [d for d in dirs if d not in ['.git', 'node_modules', 'dist']]
            for f in files:
                items.append(os.path.relpath(os.path.join(root, f), self.repo_path))
        return items[:50] # Limit results

    def read_file(self, rel_path):
        try:
            with open(os.path.join(self.repo_path, rel_path), 'r') as f:
                return f.read()
        except Exception as e:
            return str(e)

    def write_file(self, rel_path, content):
        path = os.path.join(self.repo_path, rel_path)
        try:
            # Create directories if they don't exist
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return f"Successfully wrote to {path}"
        except Exception as e:
            return f"Error writing file: {e}"

    def search_codebase(self, query):
        """Simple grep-like search"""
        results = []
        for root, dirs, files in os.walk(self.repo_path):
            dirs[:] = [d for d in dirs if d not in ['.git', 'node_modules']]
            for file in files:
                path = os.path.join(root, file)
                try:
                    with open(path, 'r', errors='ignore') as f:
                        if query in f.read():
                            results.append(os.path.relpath(path, self.repo_path))
                except:
                    continue
        return results

    def create_pr(self, branch_name, title, body, diff_summary):
        # Local Git Ops
        repo = Repo(self.repo_path)
        current = repo.active_branch
        
        # Checkout new branch
        new_branch = repo.create_head(branch_name)
        new_branch.checkout()
        
        # Commit all changes
        repo.git.add(A=True)
        commit_msg = f"{title}\n\nGenerated by CodeCrafter AI 🤖"
        repo.index.commit(commit_msg)
        
        # Push
        origin = repo.remote(name='origin')
        origin.push(branch_name)
        
        # Reset to main
        current.checkout()

        # GitHub PR
        g = Github(self.github_token)
        # Assumes repo_url form: https://github.com/owner/repo
        repo_name = "/".join(os.getenv("REPO_URL").split("/")[-2:]).replace(".git", "")
        gh_repo = g.get_repo(repo_name)
        
        pr = gh_repo.create_pull(
            title=title,
            body=body + "\n\n" + diff_summary,
            head=branch_name,
            base="main"
        )
        return pr.html_url

    def get_current_diff(self):
        """Returns the diff of unstaged/staged changes."""
        repo = Repo(self.repo_path)
        # diff of loose changes vs HEAD
        return repo.git.diff(None) or repo.git.diff("HEAD")